name: Mobile Radar Notifier

on:
  schedule:
    - cron: '50 7 * * *'  # Se ejecuta a las 7:50 UTC de cada día (España -> UTC + 1)
  workflow_dispatch:

jobs:
  scraping_and_sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Install specific Google Chrome version 114.0.5735.90
    #  run: |
    #    wget https://storage.googleapis.com/chrome-for-testing-public/114.0.5735.90/linux64/google-chrome-stable_114.0.5735.90-1_amd64.deb -O google-chrome.deb
    #    sudo dpkg -i google-chrome.deb
    #    sudo apt-get -f install

    #- name: Install ChromeDriver 114.0.5735.90
    #  run: |
    #    wget https://storage.googleapis.com/chrome-for-testing-public/114.0.5735.90/linux64/chromedriver-linux64.zip
    #    unzip chromedriver-linux64.zip
    #    sudo mv chromedriver /usr/local/bin/
    #    sudo chmod +x /usr/local/bin/chromedriver

    #- name: Check Chrome version
    #  run: google-chrome --version

    #- name: Check ChromeDriver version
    #  run: chromedriver --version

    # Paso 1: Ejecutar el script de sincronización de interacciones de Telegram a MongoDB
    - name: Run Telegram to MongoDB sync script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION_INTERACTIONS: ${{ secrets.MONGO_COLLECTION_INTERACTIONS }}
      run: |
        python bot_interactions_updater.py

    # Paso 2: Ejecutar el script de scraping y envío de mensajes
    - name: Run Scraping & Sending messages script
      env:
        DONOSTI_RADAR_WEB: ${{ secrets.DONOSTI_RADAR_WEB }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION_INTERACTIONS: ${{ secrets.MONGO_COLLECTION_INTERACTIONS }}
        MONGO_COLLECTION_REPORTS: ${{ secrets.MONGO_COLLECTION_REPORTS }}
      run: |
        python telegram_radar_notifier_copy.py
