name: Mobile Radar Notifier

on:
  schedule:
    - cron: '50 7 * * *'  # Se ejecuta a las 7:50 UTC de cada día (España -> UTC + 1)
  workflow_dispatch:

jobs:
  scraping_and_sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso: Instalar dependencias necesarias para Google Chrome
    - name: Install dependencies for Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxss1 \
          libappindicator3-1 \
          libindicator3-7 \
          fonts-liberation \
          libnss3 \
          libgdk-pixbuf2.0-0 \
          libgbm1 \
          xdg-utils

    # Paso: Descargar e instalar Google Chrome 133.0.6943.126
    - name: Install specific Google Chrome version 133.0.6943.126
      run: |
        VERSION=133.0.6943.126
        wget https://storage.googleapis.com/chrome-for-testing-public/$VERSION/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64/chrome /usr/local/bin/google-chrome
        sudo chmod +x /usr/local/bin/google-chrome
    
    # Paso: Descargar e instalar Chromedriver 133.0.6943.126
    - name: Install chromedriver 133.0.6943.126
      run: |
        VERSION=133.0.6943.126
        wget https://storage.googleapis.com/chrome-for-testing-public/$VERSION/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # Paso: Verificar la versión de Google Chrome instalada
    - name: Check Chrome version
      run: google-chrome --version

    # Paso 1: Ejecutar el script de sincronización de interacciones de Telegram a MongoDB
    - name: Run Telegram to MongoDB sync script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION_INTERACTIONS: ${{ secrets.MONGO_COLLECTION_INTERACTIONS }}
      run: |
        python bot_interactions_updater.py

    # Paso 2: Ejecutar el script de scraping y envío de mensajes
    - name: Run Scraping & Sending messages script
      env:
        DONOSTI_RADAR_WEB: ${{ secrets.DONOSTI_RADAR_WEB }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION_INTERACTIONS: ${{ secrets.MONGO_COLLECTION_INTERACTIONS }}
        MONGO_COLLECTION_REPORTS: ${{ secrets.MONGO_COLLECTION_REPORTS }}
      run: |
        python telegram_radar_notifier.py
